### ISSUE TITLE
Pilotwings N64 

### ISSUE THREAD

**Issue by WayneMario** [meleu/RetroArch-problematic-cheevos#23] opened 2017-08-08 23:50 UTC
I have tested the following achievements in RAP64 0.54 and they work correctly, however in retroarch using either the mupen or parallel core they do not unlock:
To Bed, Bath, and Infinity
 http://retroachievements.org/Achievement/49897
Rockets Explode - But Not Today
http://retroachievements.org/Achievement/49894
I Just Lit A Rocket
http://retroachievements.org/Achievement/49891
Stuck Waiting At Luggage Return
http://retroachievements.org/Achievement/49903
What's An Airport?
http://retroachievements.org/Achievement/49900
Stuck in Airport Security
http://retroachievements.org/Achievement/49906
Thanks in advance

**Comment by meleu** [comment] 2017-08-09 00:49
@WayneMario could you confirm if you reset the cheevos before trying on RetroArch?

I'm asking because looks like your username at RetroAchievements is [Wiiner](http://retroachievements.org/User/Wiiner) and this user has those achievements unlocked. You can not unlock an already unlocked cheevo.

**Comment by meleu** [comment] 2017-08-09 00:51
@grenade44 @chewvodka sorry for tagging you guys, but you are the fellows I know that play N64. Could you confirm the issue here?

Thanks.

**Comment by WayneMario** [comment] 2017-08-09 01:36
Well i tried them before but I will make a new account and try them again

**Comment by WayneMario** [comment] 2017-08-09 02:08
Tried it again on retroarch on a new account "RetroWiiner" and the others unlocked again however these ones did not:

Stuck Waiting At Luggage Return
http://retroachievements.org/Achievement/49903
What's An Airport?
http://retroachievements.org/Achievement/49900
Rockets Explode - But Not Today
http://retroachievements.org/Achievement/49894
I Just Lit A Rocket
http://retroachievements.org/Achievement/49891

I didn't retry the perfect score ones yet but I can if necessary

**Comment by meleu** [comment] 2017-08-09 03:02
What would be of a big help is a savestate right before complete the condition to trigger the cheevo.

**Comment by chewvodka** [comment] 2017-08-09 03:03
I've actually not got N64 quite setup in my RetroPie just yet.  Was waiting on a replacement charging cable for my controller.  If this isn't solved or further tested my next week, I'll try to duplicate while on vacation.

**Comment by grenade44** [comment] 2017-08-09 06:24
Never played this game before will check it out 2night if I have a spare moment. I'm not happy with the performance of n64 on my pi 3, I mostly use the official emulators for n64.

**Comment by WayneMario** [comment] 2017-08-09 13:48
So here is a save state on the mupen core that should unlock:
To Bed, Bath, and Infinity
http://retroachievements.org/Achievement/49897
Rockets Explode - But Not Today
http://retroachievements.org/Achievement/49894
I Just Lit A Rocket
http://retroachievements.org/Achievement/49891

[Pilotwings 64 (U) [!].zip](https://github.com/meleu/RetroArch-problematic-cheevos/files/1211596/Pilotwings.64.U.zip)

**Comment by grenade44** [comment] 2017-08-09 18:54
This game is unplayable for me, your savestate need to be saved just before you land not while in the points menu. Can test if fix your save state

**Comment by WayneMario** [comment] 2017-08-09 23:07
OK here is a new one (in the parallel core). Load it from the file select screen as it might not load otherwise. also you may need to use b to descend slowly enough to max out the impact score
[Pilotwings 64 (U) [!].zip]

**Comment by grenade44** [comment] 2017-08-10 19:43
@WayneMario Thank for the save state, i can confirm that there is a problem with the achievements for this game, I got a perfect/full points and none of the above achievements unlocked. BTW im testing with user name retroarch44. hopefully @meleu & @leiradel will be able to fix the issue.

**Comment by WayneMario** [comment] 2017-08-10 21:49
To my knowledge it happens with both mupen and parallel and I think it may happen with all the class B, A and pilot cheevos, probably cause their calculated the same way

**Comment by GameDragon2k** [comment] 2017-08-11 16:35
@leiradel A quick glance at all of achievements shows that they're all using the "Add Source" function that's currently exclusive to N64. So there could be an issue with that.

**Comment by leiradel** [comment] 2017-08-11 19:53
I'll take a look

**Comment by leiradel** [comment] 2017-08-15 20:11
The save state doesn't work for me

**Comment by leiradel** [comment] 2017-08-15 20:13
Using core Mupen64Plus OpenGL 2.5 9b01671

**Comment by WayneMario** [comment] 2017-08-16 01:15
I made that most recent state in the parallel core it didn't work for me in mupen

**Comment by leiradel** [comment] 2017-08-16 19:46
It doesn't work with Parallel either, using ParaLLEl N64 2.0-rc2 29aaf3a. Maybe I'm missing something.

**Comment by grenade44** [comment] 2017-08-16 20:37
When I tested I just downed core from within retroarch. I did have to rename the save state so it matched my rom name.

**Comment by chewvodka** [comment] 2017-08-16 20:38
Achievements will only work with RetroArch.  If you're using a standalone emulator, that's why it's not working.  I think the only we have that works is the lr-mupen64 one.

**Comment by leiradel** [comment] 2017-08-16 20:39
> When I tested I just downed core from within retroarch.

Mine also came from the Core Updater.

> I did have to rename the save state so it matched my rom name.

I did that too. Maybe there's some specific configuration that is needed to make it work?

**Comment by leiradel** [comment] 2017-08-16 20:41
>  I think the only we have that works is the lr-mupen64 one.

Both cores support achievements, bit the implementation has a bug.

**Comment by grenade44** [comment] 2017-08-16 21:21
thinking about it i had to waited until the game was past the title screen as it crashed retroarch

**Comment by leiradel** [comment] 2017-08-16 22:14
> thinking about it i had to waited until the game was past the title screen as it crashed retroarch

I'm not getting crashes, loading the state just doesn't do anything.

**Comment by WayneMario** [comment] 2017-08-17 00:01
@leiradel Ok here is one made in Mupen64Plus OpenGL 2.5 9b01671.  Hopefully it works for you
[Pilotwings 64 (U) [!].zip](https://github.com/meleu/RetroArch-problematic-cheevos/files/1229788/Pilotwings.64.U.zip)

**Comment by leiradel** [comment] 2017-08-17 18:11
@WayneMario thanks, but it doesn't work either.

**Comment by leiradel** [comment] 2017-08-17 18:20
Ok, I knew I was doing something wrong. I've put the state in the correct folder and now it works ;)

I'll see what's wrong.

**Comment by leiradel** [comment] 2017-08-17 20:17
I could find two lines of code that were different from the RAP64 implementation. Fixing them didn't fix these cheevos though.

Maybe I'm doing something wrong, could someone compile RetroArch from source and double check? https://github.com/leiradel/RetroArch

**Comment by meleu** [comment] 2017-08-17 20:59
@leiradel I will.

**Comment by leiradel** [comment] 2017-08-26 16:18
@meleu, I've done some changes to the code, please pull them before testing the cheevos please.

**Comment by meleu** [comment] 2017-08-26 17:06
OK, will try it tonight. ;-)

**Comment by meleu** [comment] 2017-08-27 01:26
@leiradel I've build your master branch and noticed that its version is 1.6.5 (not a problem, just noticed it). I was able to load the state @WayneMario posted [here](https://github.com/meleu/RetroArch-problematic-cheevos/issues/23#issuecomment-322931960), but once the state is loaded I didn't get any cheevo.

Not sure if there's more to do. I just loaded and it looks like the end of a stage...

**Comment by leiradel** [comment] 2017-08-27 17:21
@WayneMario can you confirm that the save state you provided was taken just *before* the achievement would be awarded, and not just after?

**Comment by WayneMario** [comment] 2017-08-27 17:38
@leiradel In RAP64 the achievement would unlock at the medal awarded screen so it should unlock them

**Comment by leiradel** [comment] 2017-08-27 17:46
@meleu do you know this screen? @WayneWario can you post a screen shot of that screen?

**Comment by WayneMario** [comment] 2017-08-27 17:51
will do

**Comment by WayneMario** [comment] 2017-08-27 17:59
These may differ as I used a different challenge and got a different score but they should be very similar
This first:
![pilotwings 64 u -170827-185429](https://user-images.githubusercontent.com/15003481/29752622-b65708a8-8b59-11e7-9c60-c98b439946bd.png)
followed by this:
![pilotwings 64 u -170827-185449](https://user-images.githubusercontent.com/15003481/29752624-c2531bba-8b59-11e7-84c1-953f96682002.png)
The achievement should pop up at the start of the second screen

**Comment by meleu** [comment] 2017-08-27 23:31
Damn'it! Sorry guys, but I ~~hate~~ don't like N64 controllers!

When I load that state I see this screen:

![pilotwings 64 usa -170827-202209](https://user-images.githubusercontent.com/8508804/29754966-64240d44-8b66-11e7-909c-92b1f6b365a5.png)

But as I don't have a controller with analogs I'm unable to press down and choose Next! :angry: 

Hey @WayneMario would you be kind enough to load your own state, press down twice to put the cursor in the "Next" option and then save the state again?

I think this is the only way I have to test it... :/

**Comment by leiradel** [comment] 2017-08-27 23:34
He'd need the build with the fixes. Can't you remap the controller to make it work?

**Comment by meleu** [comment] 2017-08-27 23:53
OK, I managed to get borrowed a PlayStation 2 controller.

Loaded the state, choose Next and no cheevos... :(

![pilotwings 64 usa -170827-204831](https://user-images.githubusercontent.com/8508804/29755149-b958a402-8b69-11e7-9699-06713c77ed29.png)

![pilotwings 64 usa -170827-204856](https://user-images.githubusercontent.com/8508804/29755151-c1a4e42c-8b69-11e7-9896-da0657ec81d1.png)

**Comment by GameDragon2k** [comment] 2017-11-24 21:11
I took another look at these achievements and they seem to be working fine now, including the savestate @WayneMario posted. 

**Shiver Me Hang Gliders**
**You're the Frosty Wind Beneath My Wings**
**When Ever-Frost Freezes Over**
**I Just Lit A Rocket**
**Rockets Explode - But Not Today**
**To Bed, Bath, and Infinity**

All of these achievements worked for me on the first attempt.

![image](https://user-images.githubusercontent.com/3225327/33223852-b5ba0580-d131-11e7-9ce5-374c2ad35d5f.png)

Unless someone else has issues with these currently, I think this issue can be closed @meleu.

**Comment by meleu** [comment] 2017-11-24 21:22
That's awesome! Will test it when I get home and then close this issue. ;-)

**Comment by meleu** [comment] 2017-11-30 16:02
@WayneMario I'm closing this issue. Update your RetroArch **and** the N64 core you're using and test it again, please.

**Closed by meleu** 2017-11-30 16:02 UTC
