### ISSUE TITLE
Solitaire-NES

### ISSUE THREAD

**Issue by chewvodka** [meleu/RetroArch-problematic-cheevos#25] opened 2017-08-28 17:46 UTC
Seems like an easy enough set of cheevos.  But they don't pop in RetroArch.
http://retroachievements.org/Game/6869

No real reason to have a save state file, but since it's an unlicensed rom, I can upload the rom itself.  So 2 of them should be easy to pop right away,, 

- Change of Scenery (http://retroachievements.org/Achievement/37533)
Just gotta change the colors/etc.
- You were close... (http://retroachievements.org/Achievement/37532)
Just gotta lose..

The other 2 require winning, turn sound off and win and just win.  I tried playing this game (with a matching hash thanks to @meleu's scripts) in QuickNES and it just returns back to the game list.  It probably doesn't work because it's not licensed and doesn't have headers maybe?  I also tried playing it FCEUMM and Nestopia.  Both of them will run in those cores, and display available achievements in RetroArch, but they don't pop.

**Comment by meleu** [comment] 2017-08-28 18:41
Did you test those cheevos with RANes?

Remember the message you saw when opening an issue here:

Before opening an issue, keep in mind that this issue tracker is for reporting **cheevos problems when running in RetroArch AND NO PROBLEMS IN OFFICIAL RetroAchievements EMULATORS**.

In order to make somebody take a look into the issue you're reporting, please **assure that the problem doesn't happen when playing in official emulators**.

**Comment by chewvodka** [comment] 2017-08-28 19:10
No, I only  use Retroarch.  I assume they work fine in the official emulator because when you look at the game on the RetroAchievements website, they have been earned by others.

**Comment by grenade44** [comment] 2017-08-29 00:24
Looking at the comments on the game page looks like there is a lot of issues with this game, I will check out the game tomorrow in RANes. Looks like a easy complete if they do work lol

**Comment by chewvodka** [comment] 2017-08-29 00:27
Yeah that's why I started playing it.  :D

**Comment by meleu** [comment] 2017-10-01 21:06
@chewvodka 
[Change of Scenery](http://retroachievements.org/Achievement/37533) worked fine for me.

I'm starting to believe it's a false positive report

Gonna try the other cheevos.

**Comment by meleu** [comment] 2017-10-01 21:42
I've got the other cheevos as well.

Closing this issue.

**Closed by meleu** 2017-10-01 21:42 UTC

**Comment by chewvodka** [comment] 2017-10-02 00:29
Shouldn't it still be open if it's still an issue for me on the RetroPie version?  It's a problematic cheevo for me, in RetroArch.  That's why I reported it.  '\shrug/'

**Comment by meleu** [comment] 2017-10-02 00:52
Sorry bro, but we use this issue tracker to list stuff that we need to take a look in order to make RetroArch more and more compatible with RetroAchievements. Since it's working on an updated RetroArch/fceumm, the problem is on your end.

The issue being closed is a sign for you to think "oh! I need to update my RetroArch/fceumm and try again."

If you need some help you can continue the conversation here, but the issue is closed. ;-)

Cheers!

**Comment by chewvodka** [comment] 2017-10-02 01:09
No worries.  :)  I'll give updating a go.
