### ISSUE TITLE
Pilotwings N64 (Paralell Core)

### ISSUE THREAD

**Issue by WayneMario** [meleu/RetroArch-problematic-cheevos#22] opened 2017-08-08 00:08 UTC
Just wondering if there is something wrong with the class A cheevos on retroarch as got perfect on class A hang gliding and gold on rocket belt but nothing unlocked.  The cheevos for perfect scores on the tutorials unlocked fine though.

**Comment by meleu** [comment] 2017-08-08 00:18
Thanks for the report but this issue tracker is for reporting **cheevos problems when running in RetroArch AND NO PROBLEMS IN OFFICIAL EMULATORS**.

If you really want that somebody take a look into the issue you reported, please assure that the problem **doesn't happen hwn playing in official emulators**.

Also, you have to detail the steps to reproduce your issue. Post links to the game and the cheevos you're facing problems.

If the needed condition to trigger the issue is time demanding, we also need a savestate to check it.

I'm closing this issue here, when/if you do what I explained above **and confirm that it's a problem with RetroArch only**, feel free to reopen the issue.

Thanks for your comprehension and for helping to make RetroArch better. :)

**Closed by meleu** 2017-08-08 00:19 UTC
